### ISSUE TITLE
TSD is broken in multiplayer for some clients

### ISSUE THREAD

**Issue by Kill3rCat** [SachaOropeza/AH64D-Project#74]
http://puu.sh/GadbR/d60c835b53.jpg

During testing with a friend, the TSD page worked correctly for me, but my fellow tester saw the above. Our actual position was in the middle of the map, but the map appears to be centred on the 0,0,0 co-ordinate. Additionally, the map didn't zoom in and out properly for this player when he pressed the buttons on the TSD page to zoom.

Other information:
 - This was on a dedicated server.
 - The aircraft was spawned empty through Zeus
 - When we tested it a couple days ago it was working, so I have no idea why it broke for this person now

**Comment by mattysmith22** [comment]
Thank your for your feedback, that is very interesting - I haven't seen this bug before. Do other animations (engine torque values when you are flying the aircraft (doesn't always work properly when you aren't the one flying due to the rotorlib simulation being local to the pilot.)

Also, does it occur when you do not spawn it in as Zeus?

**Comment by mattysmith22** [comment]
Closed due to inactivity
