### ISSUE TITLE
Getting in and out of the vehicle in multiplayer may not work reliably

### ISSUE THREAD

**Issue by Kill3rCat** [SachaOropeza/AH64D-Project#75]
One player would get into the aircraft, but to other players he would be stuck outside the aircraft in a 'getting in' animation When the same player exited the aircraft, other players would still see him inside the aircraft; other vehicles we were using did not have this issue. This was on a dedicated server. When testing with a different person a couple days earlier, this issue did not manifest.

**Comment by mattysmith22** [comment]
I would be very surprised if we managed to do that - if it is us, it'll be that the amount of scripts this vehicle needs to run causes a large amount of lag. Desync will be the culprit here. I see you mentioned on your other issue that it was spawned in using Zeus. Could you give this a go with it spawned in using 3den?

**Comment by mattysmith22** [comment]
Closed due to inactivity
